WITH TMP AS 
	(
	SELECT 
		SUM(BASE.CNT) AS SUM_CNT
	FROM 
		(
		SELECT 
			A.MENU_NM AS CURRENT_MENU
			,B.MENU_NM AS PRIVIOUS_MENU
			,COUNT(A.MENU_NM) AS CNT
		FROM 
			(
			SELECT 
				REPLACE(LOG_ID,'ID','') *1 AS ORD_NO
				,USR_NO 
				,MENU_NM
			FROM 
				KAKAOBANK.MENU_LOG
			) A 
		LEFT JOIN
			(
			SELECT 
				REPLACE(LOG_ID,'ID','') +1 AS ORD_NO
				,USR_NO 
				,MENU_NM
			FROM 
				KAKAOBANK.MENU_LOG
			) B ON A.ORD_NO = B.ORD_NO AND A.USR_NO = B.USR_NO
		WHERE 
			1=1
			AND B.ORD_NO IS NOT NULL
		GROUP BY 
			A.MENU_NM
			,B.MENU_NM
		) BASE
	)
SELECT 
	A.MENU_NM AS CURRENT_MENU
	,B.MENU_NM AS PRIVIOUS_MENU
	,COUNT(A.MENU_NM) AS CNT
	,CAST(COUNT(A.MENU_NM) / SUM_CNT AS DECIMAL(3,3)) AS RATE
FROM 
	(
	SELECT 
		REPLACE(LOG_ID,'ID','') *1 AS ORD_NO
		,USR_NO 
		,MENU_NM
	FROM 
		KAKAOBANK.MENU_LOG
	) A 
LEFT JOIN
	(
	SELECT 
		REPLACE(LOG_ID,'ID','') +1 AS ORD_NO
		,USR_NO 
		,MENU_NM
	FROM 
		KAKAOBANK.MENU_LOG
	) B ON A.ORD_NO = B.ORD_NO AND A.USR_NO = B.USR_NO
	,TMP
WHERE 
	1=1
	AND B.ORD_NO IS NOT NULL
GROUP BY 
	A.MENU_NM
	,B.MENU_NM
	,SUM_CNT
ORDER BY 
	A.MENU_NM ASC
	,B.MENU_NM ASC 
	,COUNT(A.MENU_NM) DESC
;
	