-- EXPLAIN
SELECT DISTINCT
	MAIN.DAY
	,MAIN.MENU_NM
	,CASE 
		WHEN SUB.CNT IS NOT NULL THEN SUB.CNT 
		WHEN SUB.CNT IS NULL THEN '-'
		END AS CNT
FROM 
	(
	SELECT DISTINCT 
		DAYNAME(CAST(LOG_TKTM AS DATE)) AS DAY
		,B.MENU_NM
	FROM 
		KAKAOBANK.MENU_LOG A 
	CROSS JOIN 
		(
		SELECT DISTINCT
			MENU_NM 
		FROM 
			KAKAOBANK.MENU_LOG 
		WHERE 
			MENU_NM NOT IN ('LOGIN','LOGOUT')
		)B
	) MAIN 
LEFT JOIN 
	(
	SELECT 
		DAYNAME(CAST(LOG_TKTM AS DATE)) AS DAY
		,MENU_NM
		,COUNT(MENU_NM) AS CNT 
	FROM 
		KAKAOBANK.MENU_LOG ML 
	WHERE
		1=1
		AND ML.MENU_NM NOT IN('LOGIN','LOGOUT')
	GROUP BY 
		DAY
		,MENU_NM
	) SUB ON MAIN.MENU_NM = SUB.MENU_NM AND MAIN.DAY = SUB.DAY
ORDER BY 
     CASE
          WHEN MAIN.DAY = 'MONDAY' THEN 1
          WHEN MAIN.DAY = 'TUESDAY' THEN 2
          WHEN MAIN.DAY = 'WEDNESDAY' THEN 3
          WHEN MAIN.DAY = 'THURSDAY' THEN 4
          WHEN MAIN.DAY = 'FRIDAY' THEN 5
          WHEN MAIN.DAY = 'SATURDAY' THEN 6
          WHEN MAIN.DAY = 'SUNDAY' THEN 7
     END ASC
     ,CNT DESC
     ,MAIN.MENU_NM ASC
;	








