SELECT DISTINCT
	MAIN.DAY
	,MAIN.MENU_NM
	,CASE 
		WHEN SUB.CNT IS NOT NULL THEN SUB.CNT 
		WHEN SUB.CNT IS NULL THEN '-'
		END AS CNT
FROM 
	(
	SELECT 
		DAYNAME(CAST(LOG_TKTM AS DATE)) AS DAY
		,B.MENU_NM
	FROM 
		KAKAOBANK.MENU_LOG A 
	CROSS JOIN 
		(
		SELECT DISTINCT 
			MENU_NM 
		FROM 
			KAKAOBANK.MENU_LOG 
		WHERE 
			MENU_NM NOT IN ('login','logout')
		)B
	) MAIN 			-- 날짜/메뉴명 카테시안 곱구성
LEFT JOIN 
	(
	SELECT 
		DAYNAME(CAST(LOG_TKTM AS DATE)) AS DAY
		,MENU_NM
		,COUNT(MENU_NM) AS CNT 
	FROM 
		KAKAOBANK.MENU_LOG ML 
	WHERE
		1=1
		AND ML.MENU_NM NOT IN('login','logout')
	GROUP BY 
		DAY
		,MENU_NM
	) SUB ON MAIN.MENU_NM = SUB.MENU_NM AND MAIN.DAY = SUB.DAY  -- 테이블에서 실제 날짜/메뉴별 카운트 집계 
ORDER BY 
     CASE
          WHEN MAIN.DAY = 'Monday' THEN 1
          WHEN MAIN.DAY = 'Tuesday' THEN 2
          WHEN MAIN.DAY = 'Wednesday' THEN 3
          WHEN MAIN.DAY = 'Thursday' THEN 4
          WHEN MAIN.DAY = 'Friday' THEN 5
          WHEN MAIN.DAY = 'Saturday' THEN 6
          WHEN MAIN.DAY = 'Sunday' THEN 7
     END ASC
     ,CNT DESC
     ,MAIN.MENU_NM ASC
;	