SELECT DISTINCT
	BASE.USR_NO
	,CASE
		WHEN REPLACE(RIGHT(BASE.RSDT_NO ,7),'*','') IN ('1','3','5','7') THEN 'MALE'
		WHEN REPLACE(RIGHT(BASE.RSDT_NO ,7),'*','') IN ('2','4','6','8') THEN 'FEMALE'
		ELSE '-'
	END AS GENDER
	,CASE
		WHEN SUBSTR(RSDT_NO ,7,1) IN(1,2,5,6) THEN YEAR('2020-06-28') - YEAR(CAST(CONCAT('19',LEFT(RSDT_NO,6)) AS DATE))
		WHEN SUBSTR(RSDT_NO ,7,1) IN(3,4,7,8) THEN YEAR('2020-06-28') - YEAR(CAST(CONCAT('20',LEFT(RSDT_NO,6)) AS DATE))
		ELSE '-'
		END AS AGE
	,LOC_01.LOC_NM
	,LOC_02.LOC_NM AS PRIVOUS_LOC_NM
	,CASE
		WHEN MCCO.MCCO_NM IS NOT NULL THEN MCCO.MCCO_NM
		ELSE '-'
	END AS MCCO_NM
	,IDX.INST_DTM
	,MODE.MENU_NM AS MODE_MENU_MN
	,LAST_MENU.MENU_NM AS LAST_MENU_NM
FROM 
	KAKAOBANK.USR_INFO_CHG_LOG BASE 
LEFT JOIN 
	(
	SELECT 
		BASE.USR_NO
		,BASE.MCCO_NM 
	FROM 
		(
		SELECT
			USR_NO
			,LOG_ID 
			,MCCO_NM 
			,ROW_NUMBER () OVER(PARTITION BY USR_NO ORDER BY LOG_ID DESC) AS MCCO_NO
		FROM 
			KAKAOBANK.USR_INFO_CHG_LOG
		WHERE 
			1=1
			AND MCCO_NM NOT IN('')
		) BASE
	WHERE 
		1=1
		AND BASE.MCCO_NO = 1
	) MCCO ON BASE.USR_NO = MCCO.USR_NO  -- 통신사 기준 subquery
LEFT JOIN 
	(
	SELECT 
		BASE.USR_NO
		,BASE.INST_DTM
	FROM 
		(
		SELECT
			USR_NO
			,LEFT(LOG_TKTM ,8) AS INST_DTM 
			,ROW_NUMBER () OVER(PARTITION BY USR_NO) AS ORD_NO
		FROM 
			KAKAOBANK.USR_INFO_CHG_LOG
		WHERE 
			1=1
		) BASE 
	WHERE
		1=1
		AND BASE.ORD_NO =1
	) IDX ON BASE.USR_NO = IDX.USR_NO -- 로그기준 마지막 일시 탐색
LEFT JOIN 
	(
	SELECT 
		BASE.USR_NO 
		,BASE.LOC_NM
	FROM 
		(
		SELECT DISTINCT
			USR_NO
			,LOG_ID 
			,LOC_NM 
			,ROW_NUMBER () OVER(PARTITION BY USR_NO ORDER BY LOG_ID DESC) AS LOC_NO
		FROM 
			KAKAOBANK.USR_INFO_CHG_LOG
		WHERE 
			1=1
			AND LOC_NM NOT IN('')
		) BASE
	WHERE 
		1=1
		AND BASE.LOC_NO =1	
	) LOC_01 ON BASE.USR_NO = LOC_01.USR_NO -- 마지막 위치 
LEFT JOIN 
	(
	SELECT 
		BASE.USR_NO 
		,BASE.LOC_NM
	FROM 
		(
		SELECT
			USR_NO
			,LOG_ID 
			,LOC_NM 
			,ROW_NUMBER () OVER(PARTITION BY USR_NO ORDER BY LOG_ID DESC) AS LOC_NO
		FROM 
			KAKAOBANK.USR_INFO_CHG_LOG
		WHERE 
			1=1
			AND LOC_NM NOT IN('')
		) BASE
	WHERE 
		1=1
		AND BASE.LOC_NO =2	
	) LOC_02 ON BASE.USR_NO = LOC_02.USR_NO -- 마지막에서 두번째 위치 
JOIN
	(
	SELECT 
		*
	FROM 
		(
		SELECT
			USR_NO 
			,MENU_NM
			,COUNT(MENU_NM) AS MENU_CNT
			,ROW_NUMBER() OVER(PARTITION BY USR_NO ORDER BY COUNT(MENU_NM) DESC) AS MENU_NO
		FROM 
			KAKAOBANK.MENU_LOG
		WHERE 
			1=1
			AND MENU_NM NOT IN ('login','logout')
		GROUP BY 
			USR_NO 
			,MENU_NM
		ORDER BY
			USR_NO
			,COUNT(MENU_NM) DESC
			) BASE
	WHERE 
		1=1
		AND BASE.MENU_NO =1	
	) MODE ON BASE.USR_NO = MODE.USR_NO -- 최빈값 추출 subquery
JOIN
	(
	SELECT 
		*
	FROM 
		(
		SELECT DISTINCT
			USR_NO
			,MENU_NM
			,ROW_NUMBER() OVER(PARTITION BY USR_NO ORDER BY LOG_ID DESC) AS MENU_NO
		FROM 
			KAKAOBANK.MENU_LOG
		WHERE 
			1=1
			AND MENU_NM NOT IN ('login','logout') -- LOGIN/LOGOUT 빼는게 맞나?
		) BASE 
	WHERE 
		1=1
		AND BASE.MENU_NO = 1	
	) LAST_MENU ON BASE.USR_NO = LAST_MENU.USR_NO -- 로그기준 마지막 활동 메뉴 추출
WHERE 
	1=1
	AND RSDT_NO NOT IN('')
ORDER BY 
	BASE.USR_NO ASC
;