-- 회원정보까지만 우선 추출 반영, 메뉴 이동 내역 추가 반영 예정

SELECT DISTINCT
	BASE.USR_NO
	,REPLACE(RIGHT(BASE.RSDT_NO ,7),'*','') AS GENDER
	,LEFT(BASE.RSDT_NO,6) AS BRTH_DATE
	,LOC_01.LOC_NM
	,LOC_02.LOC_NM AS PRIVOUS_LOC_NM
	,MCCO.MCCO_NM
	,IDX.INST_DTM
FROM 
	KAKAOBANK.USR_INFO_CHG_LOG BASE 
LEFT JOIN 
	(
	SELECT 
		BASE.USR_NO
		,BASE.MCCO_NM 
	FROM 
		(
		SELECT
			USR_NO
			,LOG_ID 
			,MCCO_NM 
			,ROW_NUMBER () OVER(PARTITION BY USR_NO ORDER BY LOG_ID DESC) AS MCCO_NO
		FROM 
			KAKAOBANK.USR_INFO_CHG_LOG
		WHERE 
			1=1
			AND MCCO_NM NOT IN('')
		) BASE
	WHERE 
		1=1
		AND BASE.MCCO_NO = 1
	) MCCO ON BASE.USR_NO = MCCO.USR_NO
LEFT JOIN 
	(
	SELECT 
		BASE.USR_NO
		,BASE.INST_DTM
	FROM 
		(
		SELECT
			USR_NO
			,LEFT(LOG_TKTM ,8) AS INST_DTM 
			,ROW_NUMBER () OVER(PARTITION BY USR_NO) AS ORD_NO
		FROM 
			KAKAOBANK.USR_INFO_CHG_LOG
		WHERE 
			1=1
		) BASE 
	WHERE
		1=1
		AND BASE.ORD_NO =1
	) IDX ON BASE.USR_NO = IDX.USR_NO
LEFT JOIN 
	(
	SELECT 
		BASE.USR_NO 
		,BASE.LOC_NM
	FROM 
		(
		SELECT DISTINCT
			USR_NO
			,LOG_ID 
			,LOC_NM 
			,ROW_NUMBER () OVER(PARTITION BY USR_NO ORDER BY LOG_ID DESC) AS LOC_NO
		FROM 
			KAKAOBANK.USR_INFO_CHG_LOG
		WHERE 
			1=1
			AND LOC_NM NOT IN('')
		) BASE
	WHERE 
		1=1
		AND BASE.LOC_NO =1	
	) LOC_01 ON BASE.USR_NO = LOC_01.USR_NO
LEFT JOIN 
	(
	SELECT 
		BASE.USR_NO 
		,BASE.LOC_NM
	FROM 
		(
		SELECT
			USR_NO
			,LOG_ID 
			,LOC_NM 
			,ROW_NUMBER () OVER(PARTITION BY USR_NO ORDER BY LOG_ID DESC) AS LOC_NO
		FROM 
			KAKAOBANK.USR_INFO_CHG_LOG
		WHERE 
			1=1
			AND LOC_NM NOT IN('')
		) BASE
	WHERE 
		1=1
		AND BASE.LOC_NO =2	
	) LOC_02 ON BASE.USR_NO = LOC_02.USR_NO 
WHERE 
	1=1
	AND RSDT_NO NOT IN('')
;